apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{ toYaml .Values.labels | nindent 4 }}
spec:
  template:
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: {{ .Chart.Name }}
          app.kubernetes.io/version: {{ .Chart.AppVersion }}
          {{ toYaml .Values.labels | nindent 10 }}
      replicas: {{ .Values.replicaCount }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
