image:
  repository: tutum/hello-world
  pullPolicy: IfNotPresent
  # digest: ""

labels:
  app.kubernetes.io/component: application
  app.kubernetes.io/managed-by: helm

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

containerPort:
  http: 80

resources:
  limits:
    cpu: 2m
    memory: 32Mi
  requests:
    cpu: 1m
    memory: 16Mi
