name: CI-kured

on:
  push:
    branches:
      - main
    paths:
      - 'charts/kured/**'
  workflow_dispatch:

jobs:
  test-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Lint chart
        run: helm lint charts/kured --debug

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Install chart
        run: |
          helm dependency update charts/kured
          helm install kured charts/kured --debug
