name: CI-kured

on:
  push:
    branches:
      - main
    paths:
      - charts/kured/*
  pull_request:
    paths:
    - charts/kured/*
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run Helm Lint
        run: helm lint charts/kured --debug
